[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/psf/black"
rev = "26.3.1"
hooks = [{ id = "black" }]

[[repos]]
repo = "https://github.com/PyCQA/isort"
rev = "9.0.0a3"
hooks = [{ id = "isort" }]

[[repos]]
repo = "https://github.com/PyCQA/flake8"
rev = "7.3.0"
hooks = [{ id = "flake8" }]

[[repos]]
repo = "https://github.com/python-poetry/poetry"
rev = "2.3.4"
hooks = [{ id = "poetry-check" }, { id = "poetry-lock" }]

[[repos]]
repo = "https://github.com/markdownlint/markdownlint"
rev = "v0.15.0"
hooks = [{ id = "markdownlint" }]
