[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/python-poetry/poetry"
rev = "2.3.4"
hooks = [{ id = "poetry-check" }, { id = "poetry-lock" }]

[[repos]]
repo = "https://github.com/markdownlint/markdownlint"
rev = "v0.15.0"
hooks = [{ id = "markdownlint" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12"  # Ruff version.
hooks = [
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },
  { id = "ruff-format", types_or = ["python", "pyi"] },
]
