default_language_version.ruby = "3.3.5"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/psf/black"
rev = "25.1.0"
hooks = [{ id = "black" }]

[[repos]]
repo = "https://github.com/PyCQA/isort"
rev = "6.0.1"
hooks = [{ id = "isort" }]

[[repos]]
repo = "https://github.com/PyCQA/flake8"
rev = "7.3.0"
hooks = [{ id = "flake8" }]

[[repos]]
repo = "https://github.com/python-poetry/poetry"
rev = "2.1.3"
hooks = [{ id = "poetry-check" }, { id = "poetry-lock" }]

[[repos]]
repo = "https://github.com/markdownlint/markdownlint"
rev = "v0.12.0"
hooks = [{ id = "markdownlint" }]
