[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "dstamp"
version = "1.0.0"
description = "CLI app for generating timestamps for use in Discord chats."
authors = [{ name = "Mariusz Tang", email = "dev@mariusztang.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer (>=0.16.0,<0.17.0)",
    "clipman (>=3.3.1,<4.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
]
keywords = ["discord", "timestamp", "generator"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Communications :: Chat",
    "Environment :: Console",
]

[project.scripts]
dstamp = "dstamp.main:app"

[project.urls]
Repository = "https://github.com/mariusz-tang/dstamp"
Issues = "https://github.com/mariusz-tang/dstamp/issues"

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
coverage = "^7.8.2"
freezegun = "^1.5.2"
pre-commit = "^4.2.0"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.coverage.run]
branch = true
command_line = "-m pytest"
source = ["dstamp"]
omit = ["dstamp/__main__.py", "dstamp/console.py"]

[tool.coverage.report]
skip_empty = true
skip_covered = true

[tool.coverage.html]
skip_empty = true
skip_covered = true

[tool.isort]
profile = "black"
